spring.datasource.url=jdbc:mysql://localhost:3306/fintech_db
spring.datasource.username=jlpp1TU5AL
spring.datasource.password=jlpp1TU5AL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Ejecuta los scripts de esquema y datos al iniciar
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

spring.jpa.hibernate.ddl-auto=update

# JWT
app.jwt.secret=vXB8QBhtR+R1LOdUZACsXXBT8vrZkDcf8BA9UiNqcqqjaZj38kgA21WDiJX9TNIKBaJQ6dxnni4lr9E0NhtFlw==
app.jwt.expiration-ms=86400000

# Ollama
app.ollama.base-url=http://ollama:11434
app.ollama.model=qwen2.5:3b-instruct
app.ollama.timeout-seconds=360
